# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"k\n\x12RequestVoteRequest\x12\x15\n\rcandidateTerm\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"J\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\x15\n\rprevLeaseTime\x18\x03 \x01(\x02\"%\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06update\x18\x02 \x03(\t\"\xb2\x01\n\x14\x41ppendEntriesRequest\x12\x12\n\nleaderTerm\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\x12\x1a\n\x12remainingLeaseTime\x18\x07 \x01(\x02\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x12\n\x10GetLeaderRequest\"6\n\x11GetLeaderResponse\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"+\n\rSetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x0eSetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08leaderID\x18\x02 \x01(\x05\"\x1c\n\rGetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"B\n\x0eGetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08leaderID\x18\x03 \x01(\x05\x32\x91\x02\n\x0bRaftService\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12\x32\n\tGetLeader\x12\x11.GetLeaderRequest\x1a\x12.GetLeaderResponse\x12)\n\x06SetVal\x12\x0e.SetValRequest\x1a\x0f.SetValResponse\x12)\n\x06GetVal\x12\x0e.GetValRequest\x1a\x0f.GetValResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=14
  _globals['_REQUESTVOTEREQUEST']._serialized_end=121
  _globals['_REQUESTVOTERESPONSE']._serialized_start=123
  _globals['_REQUESTVOTERESPONSE']._serialized_end=197
  _globals['_ENTRY']._serialized_start=199
  _globals['_ENTRY']._serialized_end=236
  _globals['_APPENDENTRIESREQUEST']._serialized_start=239
  _globals['_APPENDENTRIESREQUEST']._serialized_end=417
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=419
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=473
  _globals['_GETLEADERREQUEST']._serialized_start=475
  _globals['_GETLEADERREQUEST']._serialized_end=493
  _globals['_GETLEADERRESPONSE']._serialized_start=495
  _globals['_GETLEADERRESPONSE']._serialized_end=549
  _globals['_SETVALREQUEST']._serialized_start=551
  _globals['_SETVALREQUEST']._serialized_end=594
  _globals['_SETVALRESPONSE']._serialized_start=596
  _globals['_SETVALRESPONSE']._serialized_end=647
  _globals['_GETVALREQUEST']._serialized_start=649
  _globals['_GETVALREQUEST']._serialized_end=677
  _globals['_GETVALRESPONSE']._serialized_start=679
  _globals['_GETVALRESPONSE']._serialized_end=745
  _globals['_RAFTSERVICE']._serialized_start=748
  _globals['_RAFTSERVICE']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
